### ISSUE TITLE
Slug automatically changed for published entry

### ISSUE THREAD

**Issue by serhiiappno** [pauloamgomes/contentful-better-slugs#16]
When opening published entry to edit - slug is changed to match title:
 - when slug is empty (eg homepage doesn't have slug) - it will be auto generated for default locale.
 - "Don't edit slug when entry is published" configuration doesn't have effect for default locale.

**Comment by pauloamgomes** [comment]
This has been fixed in the new App version  https://github.com/pauloamgomes/contentful-better-slugs-app/tree/V1.0.0
