### ISSUE TITLE
Date field does not work

### ISSUE THREAD

**Issue by RayHughes** [pauloamgomes/contentful-better-slugs#25]
First off - THANK YOU FOR THIS

I am trying to craft a URI with the following structure: `[field:category:name]/[field:title]-[field:date]` but it does not work. Date access is enabled on the extension. It seems that it cannot access date fields.

**Comment by pauloamgomes** [comment]
Hi @RayHughes , I checked and seems to be working, for example:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/102261/134587966-363ed435-a806-4ef6-9ed6-8672cb6303a3.png">

The "-" char is not supported and seems to be causing the issue

**Comment by RayHughes** [comment]
@pauloamgomes okay thanks. Is there plans to add support for it or is this an issue on contentful itself.

**Comment by pauloamgomes** [comment]
@RayHughes yeah, would say is something that should be addressed, I'll try to see if can add it, otherwise happy with a PR

**Comment by pauloamgomes** [comment]
This should be fixed in the new App - https://github.com/pauloamgomes/contentful-better-slugs-app/tree/V1.0.0
