### ISSUE TITLE
Is this UI extension working?

### ISSUE THREAD

**Issue by AndrejGajdos** [pauloamgomes/contentful-better-slugs#3]
When I try to use this UI extension, it seems like it's not working. It doesn't render an `input` element, there is only an empty box.

<img width="816" alt="Screenshot 2020-07-23 at 14 10 23" src="https://user-images.githubusercontent.com/1593758/88284874-72e34080-ccee-11ea-81b5-a979dd873815.png">

**Comment by pauloamgomes** [comment]
Yes, I have it working.

Can you provide the configuration you defined for the field?

**Comment by AndrejGajdos** [comment]
I tried the default configuration.

<img width="831" alt="Screenshot 2020-07-23 at 16 14 03" src="https://user-images.githubusercontent.com/1593758/88296964-a4183c80-ccff-11ea-8737-042387f7ebc9.png">

**Comment by pauloamgomes** [comment]
Your field is named `slug`?

**Comment by pauloamgomes** [comment]
Yeah, that's the issue, I realized that I have the field name hardcoded.. I'll need to fix that soon

**Comment by pauloamgomes** [comment]
Apologies for the inconvenience, it should be now fixed.

**Comment by AndrejGajdos** [comment]
Np, thanks for the extension. It is working now.
