### ISSUE TITLE
Extensions are deprecated. Anyone converted to an app yet?

### ISSUE THREAD

**Issue by tony-gutierrez** [pauloamgomes/contentful-better-slugs#30]
UI extensions are deprecated in Contentful, and do not function in their "compose" tool. 

Has anyone forked this into a Contentful app yet ?

**Comment by pauloamgomes** [comment]
Hey @tony-gutierrez , indeed, I wanted to do it but didn't have the time yet..

**Comment by tony-gutierrez** [comment]
I did it, it was easy, but probably not completely optimal. I will create a
repo that you can base off of if you would like.

**Comment by fimbres** [comment]
Hi @tony-gutierrez, have you created a repo for this?

**Comment by tony-gutierrez** [comment]
@fimbres Just did. https://github.com/tony-gutierrez/betterslugs

I didnt put a lot of effort into that repo (readme, etc), but the betterslugs migrated to app form is there.

**Comment by pauloamgomes** [comment]
@fimbres @tony-gutierrez this ui extension has been now ported to a new App, you can find it here: https://github.com/pauloamgomes/contentful-better-slugs-app/tree/V1.0.0
I'm archiving this repo
