### ISSUE TITLE
no transliteration from cyrilic etc.

### ISSUE THREAD

**Issue by SergeyRe** [pauloamgomes/contentful-better-slugs#5]
check : https://github.com/contentful/extensions/tree/master/samples/slug

**Comment by pauloamgomes** [comment]
Thanks @SergeyRe  for flagging, can you kindly explain better if there is a bug on the slug generation, or you are requesting a new functionality?

**Comment by SergeyRe** [comment]
No bugs ! Ofcourse -just point you a lack of functionality solved at another  project -may be useful for you

**Comment by pauloamgomes** [comment]
Replacing slug library with speaking url as mentioned by @SergeyRe
